"""Verified fix preparation contracts and runtime."""

from strix.fix.contracts import (
    BlockerKind,
    CandidateLocation,
    CheckResult,
    CheckStatus,
    CommandSpec,
    FileManifestEntry,
    FindingContext,
    FixCandidateV1,
    FixEdit,
    FixPreparationAttempt,
    FixPreparationRequestV1,
    FixPreparationResultV1,
    PreparationBlocker,
    PreparationState,
    RegressionTestResult,
    RepairOutcome,
    RepairStatus,
    RepositoryTestPlan,
    ReproductionSpec,
    SourceIdentity,
    SourceIdentityKind,
    VerificationDecision,
    VerificationHarness,
    VerificationTarget,
    VerifierResult,
    candidate_from_legacy_report,
)
from strix.fix.prepare import (
    PreparationCancelledError,
    PreparationContext,
    PreparationPolicy,
    build_git_manifest,
    build_git_patch,
    prepare_fix,
)


__all__ = [
    "BlockerKind",
    "CandidateLocation",
    "CheckResult",
    "CheckStatus",
    "CommandSpec",
    "FileManifestEntry",
    "FindingContext",
    "FixCandidateV1",
    "FixEdit",
    "FixPreparationAttempt",
    "FixPreparationRequestV1",
    "FixPreparationResultV1",
    "PreparationBlocker",
    "PreparationCancelledError",
    "PreparationContext",
    "PreparationPolicy",
    "PreparationState",
    "RegressionTestResult",
    "RepairOutcome",
    "RepairStatus",
    "RepositoryTestPlan",
    "ReproductionSpec",
    "SourceIdentity",
    "SourceIdentityKind",
    "VerificationDecision",
    "VerificationHarness",
    "VerificationTarget",
    "VerifierResult",
    "build_git_manifest",
    "build_git_patch",
    "candidate_from_legacy_report",
    "prepare_fix",
]
